# Generated by Django 3.2.6 on 2021-11-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_color', models.CharField(max_length=55, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='DogDisplayGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_display_galery', models.CharField(max_length=55, verbose_name='Отображать в родителях?')),
            ],
            options={
                'verbose_name': 'Отображать в родителях?',
                'verbose_name_plural': 'Отображать в родителях?',
            },
        ),
        migrations.CreateModel(
            name='DogDisplayPuppy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_display_puppy', models.CharField(max_length=55, verbose_name='Отображать в щенках?')),
            ],
            options={
                'verbose_name': 'Отображать в щенках?',
                'verbose_name_plural': 'Отображать в щенках?',
            },
        ),
        migrations.CreateModel(
            name='DogGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_gender', models.CharField(max_length=55, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='Вес')),
                ('height', models.PositiveSmallIntegerField(default=0, verbose_name='Рост')),
                ('number_of_awards', models.PositiveSmallIntegerField(default=0, verbose_name='Число наград')),
                ('age', models.DateField(blank=True, default=0, verbose_name='age')),
                ('info', models.TextField(blank=True, verbose_name='Информация')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('pos', models.BooleanField(default=False, verbose_name='Показывать?')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color', to='puppy.dogcolor', verbose_name='Цвет')),
                ('display_galery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display', to='puppy.dogdisplaygalery', verbose_name='Отображать в галерее?')),
                ('display_puppy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display', to='puppy.dogdisplaypuppy', verbose_name='Отображать в щенках?')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_info', related_query_name='fat', to='puppy.doginfo', verbose_name='Папа')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gender', to='puppy.doggender', verbose_name='Пол')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_info', related_query_name='mot', to='puppy.doginfo', verbose_name='Мама')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DogPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_position', models.CharField(max_length=55, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='DogStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_status', models.CharField(max_length=55, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='puppy.doginfo')),
            ],
        ),
        migrations.AddField(
            model_name='doginfo',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='puppy.dogposition', verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='doginfo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='puppy.dogstatus', verbose_name='Статус'),
        ),
    ]
