# Generated by Django 3.2.6 on 2021-11-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
