# Generated by Django 3.2.6 on 2021-11-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название аккордиона')),
                ('accordion_img', models.ImageField(upload_to='', verbose_name='Изображение аккордиона')),
            ],
            options={
                'verbose_name': 'Аккордион',
                'verbose_name_plural': 'Аккордионы',
            },
        ),
        migrations.CreateModel(
            name='RecomendInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Рекомендации')),
            ],
            options={
                'verbose_name': 'Рекомендации',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='RecomendLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_title', models.TextField(verbose_name='Заголовок')),
                ('logo_img', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('logo_text', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипы',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.CreateModel(
            name='AccordionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела аккордиона')),
                ('accordion_text', models.TextField(verbose_name='Информация аккордиона')),
                ('accordion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec.accordion', verbose_name='Название аккордиона')),
            ],
            options={
                'verbose_name': 'Информацию аккордиона',
                'verbose_name_plural': 'Информация аккордиона',
            },
        ),
    ]
