# Generated by Django 3.2.6 on 2021-11-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accordiontext',
            old_name='title',
            new_name='accordion_title',
        ),
    ]
