# Generated by Django 3.2.9 on 2021-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='фотография главной страницы')),
            ],
            options={
                'verbose_name': 'фотография главной страницы',
                'verbose_name_plural': 'фотография главной страницы',
            },
        ),
    ]
